# .streamlit/secrets.toml
# This file should be created in your repository root under .streamlit/ folder
# Add this to your Streamlit Cloud secrets (don't commit this file with real keys!)

GOOGLE_API_KEY = "AIzaSyBGBEsn97OrW_zhHqofxIfPBvGoi3Cx1to"

# Optional: Add other API keys or secrets here
# OPENAI_API_KEY = "your-openai-key-here"
# HUGGINGFACE_API_KEY = "your-hf-key-here"
